version: '3.8'
services:
  petclinic:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - MYSQL_URL=jdbc:mysql://mysqlserver/technical_challenge
    volumes:
      - ./:/app

  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
